filterGroups = {
	MapChange: "ev-game",
	InitRound: "ev-game",
	InitAuth: "ev-game",
	ShutdownGame: "ev-game",
	ClientConnect: "ev-client",
	ClientDisconnect: "ev-client",
	ClientRename: "ev-client",
	ClientTeamChange: "ev-client",
	ClientSpawn: "ev-client",
	say: "ev-chat",
	sayteam: "ev-chat",
	Kill: "ev-game",
	SurvivorWinner: "ev-game",
	FlagPickup: "ev-flag",
	FlagDrop: "ev-flag",
	FlagReturn: "ev-flag",
	FlagCapture: "ev-flag",
	MapEnd: "ev-game",
	BombDrop: "ev-bomb",
	BombPickup: "ev-bomb",
	BombPlant: "ev-bomb",
	BombDefuse: "ev-bomb",
	BombExplode: "ev-bomb"
}
	
